//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSRS.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public I18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSRS.Resources.Localization.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artemisa.
        /// </summary>
        public static string Artemisa {
            get {
                return ResourceManager.GetString("Artemisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camagüey.
        /// </summary>
        public static string Camaguey {
            get {
                return ResourceManager.GetString("Camaguey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciego de Avila	.
        /// </summary>
        public static string CiegoDeAvila {
            get {
                return ResourceManager.GetString("CiegoDeAvila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cienfuegos.
        /// </summary>
        public static string Cienfuegos {
            get {
                return ResourceManager.GetString("Cienfuegos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crudo.
        /// </summary>
        public static string Crudo {
            get {
                return ResourceManager.GetString("Crudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FuelOil.
        /// </summary>
        public static string FuelOil {
            get {
                return ResourceManager.GetString("FuelOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasoline.
        /// </summary>
        public static string Gasoline {
            get {
                return ResourceManager.GetString("Gasoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granma.
        /// </summary>
        public static string Granma {
            get {
                return ResourceManager.GetString("Granma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guantánamo.
        /// </summary>
        public static string Guantanamo {
            get {
                return ResourceManager.GetString("Guantanamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holguín.
        /// </summary>
        public static string Holguin {
            get {
                return ResourceManager.GetString("Holguin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isla de la Juventud.
        /// </summary>
        public static string IslaJuventud {
            get {
                return ResourceManager.GetString("IslaJuventud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JetFuel.
        /// </summary>
        public static string JetFuel {
            get {
                return ResourceManager.GetString("JetFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Habana.
        /// </summary>
        public static string LaHabana {
            get {
                return ResourceManager.GetString("LaHabana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las Tunas.
        /// </summary>
        public static string LasTunas {
            get {
                return ResourceManager.GetString("LasTunas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LubricatingOil.
        /// </summary>
        public static string LubricatingOil {
            get {
                return ResourceManager.GetString("LubricatingOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matanzas.
        /// </summary>
        public static string Matanzas {
            get {
                return ResourceManager.GetString("Matanzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayabeque.
        /// </summary>
        public static string Mayabeque {
            get {
                return ResourceManager.GetString("Mayabeque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros.
        /// </summary>
        public static string Otros {
            get {
                return ResourceManager.GetString("Otros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinar del Río.
        /// </summary>
        public static string PinarDelRio {
            get {
                return ResourceManager.GetString("PinarDelRio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Santiago de Cuba.
        /// </summary>
        public static string SantiagoDeCuba {
            get {
                return ResourceManager.GetString("SantiagoDeCuba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sancti Spíritus.
        /// </summary>
        public static string SantiSpiritus {
            get {
                return ResourceManager.GetString("SantiSpiritus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransitionZone.
        /// </summary>
        public static string TransitionZone {
            get {
                return ResourceManager.GetString("TransitionZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Desconocido.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villa Clara.
        /// </summary>
        public static string VillaClara {
            get {
                return ResourceManager.GetString("VillaClara", resourceCulture);
            }
        }
    }
}
